networks:
  nfbs_dev:
    external: true
services:
  laravel:
    container_name: kantin_nfbs
    restart: unless-stopped
  
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /home/nfbsb/.env/.env.kantin
    ports:
    - "7060:80"
    networks:
      - nfbs_dev