networks:
  nfbs_dev:
    external: true
services:
  laravel:
    container_name: kantin_nfbs
    restart: unless-stopped
  
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /home/nfbsb/asset/koperasi:/var/www/html/storage/app/public
      
    ports:
    - "7060:80"
    networks:
      - nfbs_dev